import Head from 'next/head';
import React, { useState } from 'react';

import { Container, Content, Navigation, Section } from './styles';

import { Header } from '@/core/components/Header';
import { SectionTitle } from '@/core/components/SectionTitle';
import { Post } from '@/core/components/Post';
import { Menu } from '@/core/components/Menu';

import { HPosts } from '@/core/components/HPosts';
import { VPosts } from '@/core/components/VPosts';
import { useTheme } from 'styled-components';
import Link from 'next/link';

export const Home: React.FC = (props) => {

  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const theme = useTheme()

  return (
    <>
      <Head>
        <title>Home | GitHub Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container isMenuOpen={isMenuOpen}>
        {isMenuOpen && <Menu setIsMenuOpen={setIsMenuOpen} isMenuOpen/>}
        <Header setIsMenuOpen={setIsMenuOpen} />
        <Section>
          <Navigation>
            <li>
              <Link href="/#latest_publications">Ultimas publicações</Link>
            </li>
            <li>
              <Link href="/#most_relevant">Mais relevantes</Link>
            </li>
          </Navigation>
        </Section>
        <Content>
          <Section id='latest_publications'>
            <SectionTitle barColor={theme.colors.purple}>Ultimas publicações</SectionTitle>
            <VPosts>
              <Post 
                author='hugomos' 
                title='Inteligência Artificial: como a tecnologia está transformando nossas vidas'
              />
              <Post 
                author='flpfontes' 
                title='Blockchain: a tecnologia que está revolucionando a forma como fazemos negócios' 
              />
            </VPosts>
          </Section>
          
          <Section id='most_relevant'>
            <SectionTitle barColor={theme.colors.pink}>Mais relevantes</SectionTitle>
            <HPosts>
              <Post 
                author='hugomos' 
                title='Por que você deve se preocupar com a segurança dos seus dados pessoais'
                content='A segurança dos dados pessoais é um tema cada vez mais importante na era digital em que vivemos. Com a crescente quantidade de informações que compartilhamos online, é crucial entendermos os riscos associados a isso.'
                image='/images/placeholder-image-4.jpg'
              />
              <Post 
                author='flpfontes' 
                title='Da Inteligência Artificial à Nanotecnologia: Descubra as Últimas Novidades em Tecnologia Médica'
                content='Os avanços na tecnologia médica estão acontecendo a uma velocidade surpreendente, com novas inovações surgindo em um ritmo constante. Desde a inteligência artificial até a nanotecnologia, as últimas novidades estão transformando a forma como a medicina é praticada.'
                image='/images/placeholder-image-3.jpg'
              />
              <Post 
                author='flpfontes' 
                title='O lado sombrio da tecnologia: como a inteligência artificial pode ser usada para fins maliciosos'
                content='A inteligência artificial é uma das tecnologias mais promissoras e revolucionárias do século XXI. No entanto, como acontece com qualquer tecnologia avançada, existe sempre o risco de que seja usada para fins maliciosos.'
                image='/images/placeholder-image.jpg'
              />
              <Post 
                author='flpfontes' 
                title='A nova onda das startups: como a tecnologia está transformando setores tradicionais'
                content='As startups estão reinventando setores como o financeiro, com novas formas de pagamento e empréstimo; o transporte, com aplicativos de carona e de compartilhamento de bicicletas e patinetes; e a saúde, com soluções que melhoram a eficiência dos serviços médicos.'
                image='/images/placeholder-image-2.jpg'
              />
            </HPosts>
          </Section>
        </Content>
      </Container>
    </>
  );
}
